Dijkstra.out: Dijkstra.o graph.o heap.o hash.o
	g++ -o Dijkstra.out Dijkstra.o graph.o heap.o hash.o

Dijkstra.o: Dijkstra.cpp
	g++ -c Dijkstra.cpp

graph.o: graph.cpp graph.h
	g++ -c graph.cpp

heap.o: heap.cpp heap.h
	g++ -c heap.cpp

hash.o: hash.cpp hash.h
	g++ -c hash.cpp


